In [8]:
import numpy as np
from collections import Counter

In [2]:
data = np.load('raw_data.npy',allow_pickle=1)

In [3]:
data

array([array([-127, -162, -197, ...,  -18,  -22,  -21], dtype=int16),
       array([128, 157, 189, ...,   0,   1,   2], dtype=int16),
       array([ 56,  73,  85, ..., -64, -36, -20], dtype=int16), ...,
       array([-202, -235, -272, ..., -313, -173,  -52], dtype=int16),
       array([-227, -297, -374, ...,  -54,  -44,  -36], dtype=int16),
       array([-237, -286, -338, ...,  -16,  -17,  -18], dtype=int16)],
      dtype=object)

In [6]:
data.shape

(8528,)

In [4]:
labels = np.load('raw_labels.npy',allow_pickle=1)

In [5]:
labels

array([0, 0, 0, ..., 0, 0, 0])

In [7]:
labels.shape

(8528,)

In [9]:
Counter(labels)

Counter({0: 5076, 1: 758, 2: 2415, 3: 279})